
public class Aritmatika extends javax.swing.JFrame {
    String jns = "";
    int jml;
   
    
    public Aritmatika() {
        initComponents();
        getJumlah();
        setJenis();
        panel.setVisible(false);
        pilihanbil.setEnabled(false);
        bil3.setVisible(false);
        bil4.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        bil1.setVisible(false);
        bil2.setVisible(false);
        b1.setVisible(false);
        b2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        panel = new javax.swing.JPanel();
        bil4 = new javax.swing.JLabel();
        ket = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bil1 = new javax.swing.JLabel();
        bil2 = new javax.swing.JLabel();
        bil3 = new javax.swing.JLabel();
        pilihanbil = new javax.swing.JComboBox<>();
        b1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        b4 = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(null);

        jLabel2.setText("            PROGRAM ARITMATIKA");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(280, 40, 180, 30);

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Penjumlahan", "Perkalian", "Pengurangan", "Pembagian" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        jPanel1.add(jenis);
        jenis.setBounds(516, 100, 120, 20);

        panel.setBackground(new java.awt.Color(204, 204, 255));
        panel.setLayout(null);

        bil4.setText("BILANGAN 4");
        panel.add(bil4);
        bil4.setBounds(30, 170, 70, 30);

        ket.setText("                  IKEH");
        panel.add(ket);
        ket.setBounds(260, 10, 130, 30);

        jLabel4.setText("OPERASI");
        panel.add(jLabel4);
        jLabel4.setBounds(0, 0, 50, 30);

        jLabel5.setText("JUMLAH BILANGAN");
        panel.add(jLabel5);
        jLabel5.setBounds(30, 40, 100, 30);

        bil1.setText("BILANGAN 1");
        panel.add(bil1);
        bil1.setBounds(30, 80, 80, 30);

        bil2.setText("BILANGAN 2");
        panel.add(bil2);
        bil2.setBounds(30, 110, 80, 30);

        bil3.setText("BILANGAN 3");
        panel.add(bil3);
        bil3.setBounds(30, 140, 80, 30);

        pilihanbil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        pilihanbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanbilActionPerformed(evt);
            }
        });
        panel.add(pilihanbil);
        pilihanbil.setBounds(200, 50, 80, 20);
        panel.add(b1);
        b1.setBounds(190, 80, 100, 20);
        panel.add(b2);
        b2.setBounds(190, 110, 100, 20);
        panel.add(b3);
        b3.setBounds(190, 140, 100, 20);
        panel.add(b4);
        b4.setBounds(190, 170, 100, 20);

        hitung.setText("HITUNG");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        panel.add(hitung);
        hitung.setBounds(290, 200, 71, 23);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        panel.add(jTextField1);
        jTextField1.setBounds(140, 240, 330, 70);

        jPanel1.add(panel);
        panel.setBounds(50, 140, 620, 340);

        jLabel3.setText("           JENIS ARITMATIKA");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 90, 180, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 690, 500);

        setBounds(0, 0, 794, 547);
    }// </editor-fold>//GEN-END:initComponents

    private void pilihanbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanbilActionPerformed
        // TODO add your handling code here:
        getJumlah();
    }//GEN-LAST:event_pilihanbilActionPerformed
        public void getJumlah(){
            if(pilihanbil.getSelectedItem().equals("2")){
                bil3.setVisible(false);
                bil4.setVisible(false);
                b3.setVisible(false);
                b4.setVisible(false);
                bil1.setVisible(true);
                bil2.setVisible(true);
                b1.setVisible(true);
                b2.setVisible(true);
                jml = 2;
            }
            else if (pilihanbil.getSelectedItem().equals("3")){
                bil1.setVisible(true);
                bil2.setVisible(true);
                b1.setVisible(true);
                b2.setVisible(true);
                bil3.setVisible(true);
                bil4.setVisible(false);
                b3.setVisible(true);
                b4.setVisible(false);
                jml = 3;
            }
            else if(pilihanbil.getSelectedItem().equals("4")){
                bil1.setVisible(true);
                bil2.setVisible(true);
                b1.setVisible(true);
                b2.setVisible(true);
                bil3.setVisible(true);
                bil4.setVisible(true);
                b3.setVisible(true);
                b4.setVisible(true);
                jml = 4;
            }
        }
    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        // TODO add your handling code here:
        setJenis();
    }//GEN-LAST:event_jenisActionPerformed
         public void setJenis(){
        if(jenis.getSelectedItem().equals("Penjumlahan")){
        jns = "Penjumlahan";
        ket.setText("Penjumlahan");
        panel.setVisible(true);
        pilihanbil.setEnabled(true);
    }
        else if (jenis.getSelectedItem().equals("Pengurangan")){
        jns = "Pengurangan";
        ket.setText("Pengurangan");
        panel.setVisible(true);
        pilihanbil.setEnabled(true);        
    }
        else if (jenis.getSelectedItem().equals("Perkalian")){
        jns = "Perkalian";
        ket.setText("Perkalian");
        panel.setVisible(true);
        pilihanbil.setEnabled(true);        
    }
        else if (jenis.getSelectedItem().equals("Pembagian")){
        jns = "Pembagian";
        ket.setText("Pembagian");
        panel.setVisible(true);
        pilihanbil.setEnabled(true);        
    }
    }
    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        Double hs1 = 0.0;
        Double a1, a2, a3, a4;
        a1 = Double.parseDouble(b1.getText().toString());
        a2 = Double.parseDouble(b2.getText().toString());
        a3 = Double.parseDouble(b3.getText().toString());
        a4 = Double.parseDouble(b4.getText().toString());
        
        if (jns.equals("Penjumlahan")){
            if(jml == 2){
                hs1 = a1 + a2;
                jTextField1.setText(""+a1+"+"+a2+"="+hs1);
            }
            if(jml == 3){
                hs1 = a1 + a2 + a3;
                jTextField1.setText(""+a1+"+"+a2+"+"+a3+"="+hs1);
            }
            if(jml == 4){
                hs1 = a1 + a2 + a3 +a4;
                jTextField1.setText(""+a1+"+"+a2+"+"+a3+"+"+a4+"="+hs1);
            }
        }
        else if(jns.equals("Pengurangan")){
            if (jml == 2){
                hs1 = a1 - a2;
                jTextField1.setText(""+a1+ " - " + a2 + "="+hs1);
            }
            if(jml == 3){
                hs1 = a1 - a2 - a3;
                jTextField1.setText(""+a1+"-"+a2+"-"+a3+"="+hs1);
            }
            if(jml == 4){
                hs1 = a1 - a2 - a3 - a4;
                jTextField1.setText(""+a1+"-"+a2+"-"+a3+"-"+a4+"="+hs1);
            }
        }
        else if(jns.equals("Perkalian")){
            if (jml == 2){
                hs1 = a1 * a2;
                jTextField1.setText(""+a1+ " * " + a2 + "="+hs1);
            }
            if(jml == 3){
                hs1 = a1 * a2 * a3;
                jTextField1.setText(""+a1+"*"+a2+"*"+a3+"="+hs1);
            }
            if(jml == 4){
                hs1 = a1 * a2 * a3 * a4;
                jTextField1.setText(""+a1+"*"+a2+"*"+a3+"*"+a4+"="+hs1);
            }
        }
        else if(jns.equals("Pembagian")){
            if (jml == 2){
                hs1 = a1 / a2;
                jTextField1.setText(""+a1+ " / " + a2 + "="+hs1);
            }
            if(jml == 3){
                hs1 = a1 / a2 / a3;
                jTextField1.setText(""+a1+"/"+a2+"/"+a3+"="+hs1);
            }
            if(jml == 4){
                hs1 = a1 / a2 / a3 / a4;
                jTextField1.setText(""+a1+"/"+a2+"/"+a3+"/"+a4+"="+hs1);
            }
        }
    }//GEN-LAST:event_hitungActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aritmatika().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JLabel bil1;
    private javax.swing.JLabel bil2;
    private javax.swing.JLabel bil3;
    private javax.swing.JLabel bil4;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JLabel ket;
    private javax.swing.JPanel panel;
    private javax.swing.JComboBox<String> pilihanbil;
    // End of variables declaration//GEN-END:variables
}
