/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Skaha_AM
 */
public class PilihDokter extends javax.swing.JFrame {

    /**
     * Creates new form PilihDokter
     */
    public PilihDokter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        spesial = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        usia = new javax.swing.JTextField();
        jenis = new javax.swing.JTextField();
        gol = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        kewar = new javax.swing.JTextField();
        waktu = new javax.swing.JTextField();
        jInternalFrame1 = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("        DOKTER SPESIALIS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 410, 120, 30);

        jLabel2.setText("         PEMILIHAN DOKTER");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 20, 160, 30);

        jLabel3.setText("         PILIH DOKTER");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 70, 120, 30);

        jLabel4.setText("        IDENTITAS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 120, 120, 30);

        jLabel5.setText("       NAMA");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 170, 120, 30);

        jLabel6.setText("       ALAMAT");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 200, 120, 30);

        jLabel7.setText("        USIA");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 230, 120, 30);

        jLabel8.setText("       JENIS KELAMIN");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 260, 120, 30);

        jLabel9.setText("        GOLONGAN DARAH");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 290, 120, 30);

        jLabel10.setText("        STATUS");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 320, 120, 30);

        jLabel11.setText("        KEWARGANEGARAAN");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 350, 130, 30);

        jLabel12.setText("        WAKTU PRAKTEK");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 380, 120, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~ Pilih Salah Satu ~", "Dr. Farras Yassar", "Dr. Dian Sikahita", "Dr. Harun Ulum Fajar" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(190, 70, 150, 20);

        spesial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spesialActionPerformed(evt);
            }
        });
        getContentPane().add(spesial);
        spesial.setBounds(170, 410, 170, 20);
        getContentPane().add(nama);
        nama.setBounds(170, 170, 170, 20);

        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });
        getContentPane().add(alamat);
        alamat.setBounds(170, 200, 170, 20);

        usia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usiaActionPerformed(evt);
            }
        });
        getContentPane().add(usia);
        usia.setBounds(170, 230, 170, 20);

        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        getContentPane().add(jenis);
        jenis.setBounds(170, 260, 170, 20);

        gol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                golActionPerformed(evt);
            }
        });
        getContentPane().add(gol);
        gol.setBounds(170, 290, 170, 20);

        jTextField7.setText("jTextField1");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(170, 290, 170, 20);

        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        getContentPane().add(status);
        status.setBounds(170, 320, 170, 20);

        kewar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kewarActionPerformed(evt);
            }
        });
        getContentPane().add(kewar);
        kewar.setBounds(170, 350, 170, 20);

        waktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waktuActionPerformed(evt);
            }
        });
        getContentPane().add(waktu);
        waktu.setBounds(170, 380, 170, 20);

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(40, 120, 480, 350);

        setBounds(0, 0, 720, 542);
    }// </editor-fold>//GEN-END:initComponents

    private void spesialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spesialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spesialActionPerformed

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void usiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usiaActionPerformed

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisActionPerformed

    private void golActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_golActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_golActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void kewarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kewarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kewarActionPerformed

    private void waktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waktuActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().equals("Dr. Farras Yassar")){
    nama.setText("DR. Farras Yassar");
    alamat.setText("Jl. Surabaya 16, Malang");
    usia.setText("20 Tahun");
    jenis.setText("Laki-Laki");
    gol.setText("A");
    status.setText("Belum Menikah ");
    kewar.setText("Indonesia");
    spesial.setText("Dokter Umum");
    waktu.setText(" Pagi (07.00-15.00)");
}
        else if(jComboBox1.getSelectedItem().equals("Dr. Dian Sikahita")){
nama.setText("DR. Dian Sikahita");
alamat.setText("Jl. Veteran 3, Malang");
usia.setText("20 Tahun");
jenis.setText("Perempuan");
gol.setText("O");
status.setText("Belum Menikah");
kewar.setText("Indonesia");
spesial.setText("Dokter Gigi");
waktu.setText(" Sore (16.00-22.00)");
}
        else if(jComboBox1.getSelectedItem().equals("Dr. Harun Ulum Fajar")){
nama.setText("DR. Harun Ulum Fajar");
alamat.setText("Jl. Bandung 9, Malang");
usia.setText("20 Tahun");
jenis.setText("Laki-Laki");
gol.setText("B");
status.setText("Belum Menikah");
kewar.setText("Indonesia");
spesial.setText("Dokter Gizi");
waktu.setText(" Malam (22.00-06.00)");
}
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihDokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField gol;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jenis;
    private javax.swing.JTextField kewar;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField spesial;
    private javax.swing.JTextField status;
    private javax.swing.JTextField usia;
    private javax.swing.JTextField waktu;
    // End of variables declaration//GEN-END:variables
}
